(docs) working with images
e-Spirit/fsxa-pwa pull request #26
Opened 2021-04-22 09:36 UTC by Dramaturco

Added a working with images chapter

2021-04-28 10:04 UTC, vlapl requested changes
Some minor changes, and it's done. :)

2021-04-28 10:04 UTC, vlapl commented on docs/WorkingWithImages.md
> +The term lazy loading refers to loading certain resources at the latest possible moment as opposed to loading all resources at the initial rendering of a page. If you use the [FSXA-UI image component
As a reader I'd now like to know _why_ this "should be used sparingly".

2021-04-29 07:58 UTC, Dramaturco commented on docs/WorkingWithImages.md
> +As you can see, the data contains a URL reference that usually points towards the FirstSpirit CaaS media collection. Following the URL will yield all the available resolutions of the image (see examp
At that point you get an array of objects containing URLs pointing to individual images. So each URL should point to a singular image with the annotated resolution.

2021-05-03 07:32 UTC, vlapl approved these changes

2021-05-03 12:44 UTC, merged