docs: debugging
e-Spirit/fsxa-pwa pull request #48
Opened 2021-11-11 14:38 UTC by p-runge

tng-1024

2021-11-11 16:33 UTC, henczi-espirit reviewed
should this be checked in? (is it on purpose?)

2021-11-15 08:11 UTC, henczi-espirit requested changes
Please remove the launch.json, fix the typo in the doc and decide if you want to have the "debugger" keyword part of the documentation.

2021-11-15 11:15 UTC, p-runge commented on docs/modules/ROOT/pages/Debugging.adoc
> +=== Download EDI
Fixed

2021-11-15 11:16 UTC, p-runge commented on docs/modules/ROOT/pages/Debugging.adoc
> +Click on the launch button at the bottom bar of VS Code to launch a Chrome window where the debugger is attached to. You can set breakpoints wherever you want to debug your code by either toggling a
I assumed having a linter in the CI that wouldn't allow pushing those things. Nevertheless it's not really needed anyway, so I'll just erase it.

2021-11-15 11:18 UTC, p-runge commented on .vscode/launch.json
> +{
I'll add the whole .vscode directory to .gitignore since it seems to have been pushed by mistake initially.

2021-11-16 09:53 UTC, henczi-espirit approved these changes

2021-11-16 09:53 UTC, merged