Custom css
e-Spirit/fsxa-pwa pull request #9
Opened 2021-03-04 14:48 UTC by Dramaturco

Added the custom css and how to remove Tailwind sections to the documentation.

2021-03-04 15:11 UTC, Dramaturco commented
Be aware that we haven't talked about what the "breadcrumbs" to the upper level of pages should be called. I called them "index" but I'm not sure if that's ideal. Also I'm not sure where to place them. I had them above the headline but the linter didn't like that.

2021-03-04 19:31 UTC, tgolbs requested changes
There are just two little issues. Rest looks great.

2021-03-04 19:31 UTC, tgolbs commented on docs/css/Component.md
> +And then import and use it your component like this
*in

2021-03-04 19:31 UTC, tgolbs commented on docs/css/RemovingTailwind.md
> +Keep in mind however, that the tailwind css classes are still applied to the existing components.
Remove ```tailwind.config.js``` as well.

2021-03-05 07:49 UTC, Dramaturco commented on docs/css/Component.md
> +And then import and use it your component like this
Check

2021-03-05 07:49 UTC, Dramaturco commented on docs/css/RemovingTailwind.md
> +Keep in mind however, that the tailwind css classes are still applied to the existing components.
Check

2021-03-11 08:32 UTC, merged